### ISSUE TITLE
Fix Issue With Bot

### ISSUE THREAD

**Issue by Tnology** [LukasmanMHdude/BIDOME#19]
**Issue Type:** Bug
**Bug Severity:** Low
**Description:** There is a bug where the bot will sometimes react to my command's message with the ":trojker:" emoji instead of properly executing this command. Other users cannot seen to replicate this unintended functionality. There is no way to get a consistent result, as it happens at random. Hopefully you look into this and fix this issue.

**Comment by Bloxs** [comment]
This is intended behavior as part of #16
